version: '3' #version of docker compose 
services:
  web:                  #Service name
    build: .            #build the file in current directry
    ports:              
      - "5000:5000"
    volumes:
      - .:/app          # we are pass the current directry in the folder".:" and map it to /app in the container